"use strict";

// dummy user info
// eslint-disable-next-line no-unused-vars
var users = [{
    device_id: "dummy-1",
    name: "User-1",
    username: "User-1",
    email: "User-1@cly.com",
    organization: "Countly",
    phone: "+919882201994",
    gender: "M",
    byear: "1994"
}, {
    device_id: "dummy-2",
    name: "User-2",
    username: "User-2",
    email: "User-2@cly.com",
    organization: "Countly",
    phone: "+919882201994",
    gender: "M",
    byear: "1994"
}, {
    device_id: "dummy-3",
    name: "User-3",
    username: "User-3",
    email: "User-3@cly.com",
    organization: "Countly",
    phone: "+919882201994",
    gender: "M",
    byear: "1994"
}, {
    device_id: "dummy-4",
    name: "User-4",
    username: "User-4",
    email: "User-4@cly.com",
    organization: "Countly",
    phone: "+919882201994",
    gender: "M",
    byear: "1994"
}, {
    device_id: "dummy-5",
    name: "User-5",
    username: "User-5",
    email: "User-5@cly.com",
    organization: "Countly",
    phone: "+919882201994",
    gender: "M",
    byear: "1994"
}, {
    device_id: "dummy-6",
    name: "User-6",
    username: "User-6",
    email: "User-6@cly.com",
    organization: "Countly",
    phone: "+919882201994",
    gender: "M",
    byear: "1994"
}, {
    device_id: "dummy-7",
    name: "User-7",
    username: "User-7",
    email: "User-7@cly.com",
    organization: "Countly",
    phone: "+919882201994",
    gender: "M",
    byear: "1994"
}, {
    device_id: "dummy-8",
    name: "User-8",
    username: "User-8",
    email: "User-8@cly.com",
    organization: "Countly",
    phone: "+919882201994",
    gender: "M",
    byear: "1994"
}, {
    device_id: "dummy-9",
    name: "User-9",
    username: "User-9",
    email: "User-9@cly.com",
    organization: "Countly",
    phone: "+919882201994",
    gender: "M",
    byear: "1994"
}];